### ISSUE TITLE
Whatever happened to 2d-extras?

### ISSUE THREAD

**Issue by Crazy4bricks** [Unity-Technologies/2d-techdemos#17]
whenever I attempted to access the official 2d extras repository, nothing shows up. Did someone delete the file on accident? If not, why? If so, can it be fixed? If it can, is it being actively fixed? If it isn't, why? Transparency on such a popular asset package would be much appreciated.

**Comment by ChuanXin-Unity** [comment]
Sorry for the inconvenience caused by this.

We have made the 2d extras repository private for now, as there were some complications while trying to convert this repository to a format suitable for creating package releases for the Unity Package Manager.

We will make 2d-extras repository public again as soon as we can!

**Comment by CineTek** [comment]
How can you guys switch to a (in theory great) manifest-based package system and then all of a sudden disable one of your KEY packages without any warning whatsoever? We have multiple games in production and this breaks all of them!

**Comment by ChuanXin-Unity** [comment]
I apologize for this issue and the inconvenience it caused.

Mistakes were made and have been rectified. The 2d-extras repository is open now. Moving forward, we will get the 2d-extras to the Unity Package Manager where you can get separate fixed releases without worrying about the state of the repository.

**Comment by CineTek** [comment]
That's perfect, thank you very much!
